<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UNOonline</title>
    <link rel="stylesheet" type="text/css" href="/css/style.x23532.css"/>
</head>
<body>
<div align="center">
<h1>UNOonline</h1>
<h3>Enter your name</h3>
<form action="/add" method="post">
    <input type="text" name="name" />
    <br>
    <input type="submit" value="Create a new room">
</form>
</body>
</html>